# Generated by Django 5.1.7 on 2025-06-22 17:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country of the address",
                        max_length=255,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region or state within the country",
                        max_length=255,
                        null=True,
                        verbose_name="Region/State",
                    ),
                ),
                (
                    "subregion",
                    models.CharField(
                        blank=True,
                        help_text="Subregion or province within the region",
                        max_length=255,
                        null=True,
                        verbose_name="Subregion/Province",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City of the address",
                        max_length=255,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                (
                    "apt_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Apartment number"
                    ),
                ),
                (
                    "street_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Street number"
                    ),
                ),
                ("street", models.CharField(max_length=255, null=True)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal code",
                        max_length=10,
                        null=True,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Geographical latitude of the address",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Geographical longitude of the address",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceBooking",
            fields=[
                (
                    "profile_id",
                    models.CharField(
                        help_text="Reference to CompanyProfile ID from users service",
                        max_length=50,
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "modified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_reference", models.CharField(max_length=20, unique=True)),
                (
                    "customer_user_id",
                    models.CharField(
                        help_text="Reference to User ID from users service",
                        max_length=50,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=20)),
                ("number_of_participants", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("attended", "Attended"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to payment record in payment service",
                        max_length=100,
                    ),
                ),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("special_requests", models.TextField(blank=True)),
                ("dietary_requirements", models.TextField(blank=True)),
                ("accessibility_needs", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "booking_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("cancellation_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-booking_date"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="experiences.experiencecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Experience Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "profile_id",
                    models.CharField(
                        help_text="Reference to CompanyProfile ID from users service",
                        max_length=50,
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "modified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("tour", "Tour"),
                            ("activity", "Activity"),
                            ("event", "Event"),
                            ("fitness_class", "Fitness Class"),
                            ("music_class", "Music Class"),
                            ("art_class", "Art Class"),
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("conference", "Conference"),
                            ("concert", "Concert"),
                            ("sports_event", "Sports Event"),
                            ("cultural_event", "Cultural Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("venue_name", models.CharField(blank=True, max_length=255)),
                (
                    "duration",
                    models.DurationField(help_text="Duration of the experience"),
                ),
                ("min_participants", models.PositiveIntegerField(default=1)),
                ("max_participants", models.PositiveIntegerField()),
                ("age_restriction", models.CharField(blank=True, max_length=100)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all_levels", "All Levels"),
                        ],
                        default="all_levels",
                        max_length=20,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "includes",
                    models.TextField(
                        blank=True, help_text="What's included in the experience"
                    ),
                ),
                (
                    "excludes",
                    models.TextField(blank=True, help_text="What's not included"),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="Requirements for participants"
                    ),
                ),
                ("cancellation_policy", models.TextField(blank=True)),
                ("refund_policy", models.TextField(blank=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="experiences.address",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="experiences",
                        to="experiences.experiencecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceImage",
            fields=[
                (
                    "profile_id",
                    models.CharField(
                        help_text="Reference to CompanyProfile ID from users service",
                        max_length=50,
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "modified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="experiences/%Y/%m/%d/")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Optional video file for the experience",
                        null=True,
                        upload_to="experiences/videos/%Y/%m/%d/",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="experiences.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceReview",
            fields=[
                (
                    "profile_id",
                    models.CharField(
                        help_text="Reference to CompanyProfile ID from users service",
                        max_length=50,
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "modified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reviewer_user_id",
                    models.CharField(
                        help_text="Reference to User ID from users service",
                        max_length=50,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField()),
                (
                    "organization_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "instructor_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "venue_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "value_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("response", models.TextField(blank=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="experiences.experiencebooking",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="experiences.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceSession",
            fields=[
                (
                    "profile_id",
                    models.CharField(
                        help_text="Reference to CompanyProfile ID from users service",
                        max_length=50,
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "modified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("instructor_name", models.CharField(blank=True, max_length=255)),
                ("instructor_bio", models.TextField(blank=True)),
                (
                    "instructor_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to User ID from users service",
                        max_length=50,
                    ),
                ),
                ("max_participants", models.PositiveIntegerField()),
                ("available_spots", models.PositiveIntegerField()),
                ("booked_spots", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="experiences.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="experiences.experiencesession",
            ),
        ),
        migrations.CreateModel(
            name="ParticipantDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("dietary_requirements", models.TextField(blank=True)),
                ("medical_conditions", models.TextField(blank=True)),
                ("accessibility_needs", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="experiences.experiencebooking",
                    ),
                ),
            ],
            options={
                "ordering": ["booking", "last_name", "first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["profile_id", "is_active"],
                name="experiences_profile_a3a282_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["experience_type", "category"],
                name="experiences_experie_54aad9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="experiences_is_acti_b1de35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experiencereview",
            index=models.Index(
                fields=["experience", "is_published"],
                name="experiences_experie_9f1cbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experiencereview",
            index=models.Index(
                fields=["reviewer_user_id"], name="experiences_reviewe_b97ec4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiencesession",
            index=models.Index(
                fields=["experience", "date"], name="experiences_experie_dd99d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiencesession",
            index=models.Index(
                fields=["date", "status"], name="experiences_date_c80595_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiencebooking",
            index=models.Index(
                fields=["profile_id", "status"], name="experiences_profile_2d279f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiencebooking",
            index=models.Index(
                fields=["customer_user_id"], name="experiences_custome_a01879_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiencebooking",
            index=models.Index(
                fields=["session"], name="experiences_session_3dcda2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiencebooking",
            index=models.Index(
                fields=["booking_reference"], name="experiences_booking_1c0152_idx"
            ),
        ),
    ]
